export const BlocklyLocale = {
        Locale: "en-US",

        LXLDocumentation: "LXL Documentation",
        ExamplePlugins: "Example plugins",
        DownloadLXL: "Download LXL",

        DownloadPluginMessage: "Please enter the filename to generate",
        DownloadPluginMessageFilename: "Your filename",
        DownloadPluginMessageOk: "Click OK to start the download",

        GamemodeSurvival: "Survival",
        GamemodeCreative: "Creative",
        GamemodeAdventure: "Adventure",

        LogicCategory: "Logic",
        LoopCategory: "Loops",
        MathCategory: "Math",
        StringsCategory: "Strings",
        ListCategory: "Lists",
        VariableCategory: "Variables",
        ProcedureCategory: "Procedures",

        ConsoleInterfaceCategory: "Console Interface",
            ConsoleOutputLog: "Output log",
            ConsoleOutputColorLog: "Output colored log",
            ConsoleOutputColor: "Color",
            ConsoleDelayFunction: "Delayed function",
            ConsoleDelay: "Delay",
            ConsoleIntervalFunction: "Interval function",
            ConsoleIntervalCycle: "Period",
            ConsoleClearIntervalCycle: "Cancel Interval functions",
            ConsoleClearIntervalCycleTime: "Task ",
        BasicInterfaceCategory: "Basic Interface",
            BasicInterfaceIntegerCoordinates: "Integer Coordinates",
            BasicInterfaceFloatingPointCoordinates: "Floating point Coordinates",
            BasicInterfaceXCoordinate: "X",
            BasicInterfaceYCoordinate: "Y",
            BasicInterfaceZCoordinate: "Z",
            BasicInterfaceDimension: "Dimension/World",
            BasicInterfaceOverworld: "Overworld",
            BasicInterfaceNether: "The Nether",
            BasicInterfaceEnd: "The End",
        CommandOperationCategory: "Command Operations",
            CommandOperationOpenMainMenu: "Open the main menu",
            CommandConsole: "Console",
            CommandExecution: "Execute the command",
            CommandExecutionStatus: "Command execution status",
            CommandExecutionResult: "Command execution result",
            CommandExecutor: "command executor/player who executed command",
            CommandDescription: "Add description",
            CommandImplement: "implement",
            CommandFor: "For the command",
            CommandOf: "Of",
            CommandPlayer: "Player",
            CommandUndefined: "Undefined description",
            CommandWhen: "When",
            CommandTime: "Time",
            CommandConsoleOutput: "Output to console",
        PlayerOperationCategory: "Player Operations",
            PlayerGameName: "PlayerName",
            PlayerKickMessage: "You got kicked!",
            PlayerTranslationOne: "All online players/List of Player XUIDs",
            PlayerTranslationTwo: "Get object",
            PlayerTranslationThree: "of",
            PlayerTranslationFour: "player name",
            PlayerTranslationFive: "coordinate",
            PlayerTranslationSix: "realname",
            PlayerTranslationSeven: "IP address",
            PlayerTranslationEight: "permission level",
            PlayerTranslationNine: "OP status",
            PlayerTranslationTen: "gamemode",
            PlayerTranslationEleven: "max health",
            PlayerTranslationTwelve: "current health",
            PlayerTranslationThirteen: "inAir",
            PlayerTranslationForteen: "sneaking",
            PlayerTranslationFifteen: "Kick",
            PlayerTranslationSixteen: "Reason",
            PlayerTranslationSeventeen: "To the player",
            PlayerTranslationEighteen: "Send",
            PlayerTranslationNineteen: "Normal message",
            PlayerTranslationTwenty: "Chat message",
            PlayerTranslationTwentyOne: "Inventory message",
            PlayerTranslationTwentyTwo: "JSON Message",
            PlayerTranslationTwentyThree: "Broadcast once",
            PlayerTranslationTwentyFour: "For the player",
            PlayerTranslationTwentyFive: "Execute the following command",
            PlayerTranslationTwentySeven: "Make player say",
            PlayerTranslationTwentyEight: "Transfer player",
            PlayerTranslationTwentyNine: "to the coordinates",
            PlayerTranslationThirty: "kill player",
            PlayerTranslationThirtyOne: "make player",
            PlayerTranslationThirtyTwo: "cause",
            PlayerTranslationThirtyThree: "point damage",
            PlayerTranslationThirtyFour: "on fire",
            PlayerTranslationThirtyFive: "Second",
            PlayerTranslationThirtySix: "Rename player",
            PlayerTranslationThirtySeven: "for",
            PlayerTranslationThirtyEight: "block standing on",
            PlayerTranslationThirtyNine: "types of",
            PlayerTranslationForty: "Data value",
            PlayerTranslationFortyOne: "in the device information of",
            PlayerTranslationFortyTwo: "Average network latency",
            PlayerTranslationFortyThree: "Average network packet loss rate",
            PlayerTranslationFortyFour: "OS type",
            PlayerTranslationFortyFive: "Client",
            PlayerTranslationFortySix: "Item in main hand",
            PlayerTranslationFortySeven: "Off-hand item",
            PlayerTranslationFortyEight: "All items in the inventory",
            PlayerTranslationFortyNine: "All items in the armor slots",
            PlayerTranslationFifty: "All items in the ender chest",
            PlayerTranslationFiftyOne: "Respawn coordinates",
            PlayerTranslationFiftyTwo: "Clear objects",
            PlayerTranslationFiftyThree: "All on the body",
            PlayerTranslationFiftyFour: "thing",
            PlayerTranslationFiftyFive: "Refresh object",
            PlayerTranslationFiftySix: "'s inventory'",
            PlayerTranslationFiftySeven: "loaded block",
            PlayerTranslationFiftyEight: "Set Player",
            PlayerTranslationFiftyNine: "Permission level to",
            PlayerTranslationSixty: "The game mode is",
            PlayerTranslationSixtyOne: "Improve player",
            PlayerTranslationSixtyTwo: "Experience Level",
            PlayerTranslationSixtyThree: "Transfer Player",
            PlayerTranslationSixtyFour: "to address",
            PlayerTranslationSixtyFive: "port is",
            PlayerTranslationSixtySix: "server",
            PlayerTranslationSixtySeven: "Crash player",
            PlayerTranslationSixtyEight: "Client",
            PlayerTranslationSixtyNine: "Sidebar Title",
            PlayerTranslationSeventy: "Sidebar Object Content",
            PlayerTranslationSeventyOne: "Sidebar sorting",
            PlayerTranslationSeventyTwo: "Descending order",
            PlayerTranslationSeventyThree: "Ascending order",
}